### PR TITLE
The payload is the entire body

### PR DESCRIPTION
**Pull request by s1037989**
It seems the Github webhook API changed...?

### CODE REVIEW

**Comment by jhthorsen** [comment]
Could you find a link to the documentation? Also, travis is failing: https://travis-ci.org/jhthorsen/toadfarm/jobs/60072283

**Comment by s1037989** [comment]
This is what I based this pull request on: https://developer.github.com/webhooks/#payloads
When testing a push with my configured webhook, I saw no payload parameter.  I then checked this link and see that the payload is the whole body.  I then modified the code locally and it's been working great since!

What do you think about this?

Sorry, I don't know anything about Travis.  I know it's extremely helpful to development, but I don't know what causes Travis failures or what to do about it?

**Comment by jhthorsen** [comment]
About travis: It means that your change is breaking the unit tests.

    $ cd checked/out/git/toadfarm
    $ prove -l

I can't merge a PR when there's failing tests.

**Comment by jhthorsen** [comment]
Nevermind. I'll fix this one :smile:

**Comment by s1037989** [comment]
:+1:  Thanks!!

**Pull request merged**
