### PR TITLE
Update .travis.yml for Perl versions

### PR DESCRIPTION
**Pull request by s1037989**
I grabbed this from mojolicious/mojo.  Does this look appropriate to you?  Hopefully this will allow travis checks to start passing within Github again -- this would have caught the incomplete PR #27 and the need for follow up #28 .

### CODE REVIEW

**Comment by jhthorsen** [comment]
👍

**Comment by s1037989** [comment]
Specifically this is failing on 5.10:
```
t/command-restart.t .. ok
===(      57;0  8/?  2/?  0/?  0/?  0/?  0/?  0/?  0/? )================
#   Failed test 'no warnings'
#   at t/app-class.t line 18.
#     Structures begin differing at:
#          $got->[0] = 'Use of uninitialized value in length at /home/travis/perl5/perlbrew/perls/5.10/lib/site_perl/5.10.1/Mojo/IOLoop/Stream.pm line 125.
#     '
#     $expected->[0] = Does not exist
# Looks like you failed 1 test of 9.
t/app-class.t ........ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/9 subtests 
```
Do you want to try to fix that, or just remove 5.10 from travis?  Basically every test is full of "Use of uninitialized value in length" warnings.  Those warnings don't occur on 5.12+.

**Comment by jhthorsen** [comment]
Thanks! I made the list a bit shorter now. I was considering removing more, but it's OK for now I hope.

**Comment by s1037989** [comment]
Success!  Travis pass!  Good to see the green checkmark again.  :)

**Pull request merged**
