### PR TITLE
Fix tests for #27

### PR DESCRIPTION
**Pull request by s1037989**
Sorry, @jhthorsen !  D:

### CODE REVIEW

**Comment by jhthorsen** [comment]
That was sloppy of both of us 😞 

Thanks for the fix! ❤️

**Comment by s1037989** [comment]
Yes -- I take full responsibility!  Thanks for the quick merge!  I'll submit a PR for travis, next.

**Comment by s1037989** [comment]
Uh, oh...  sorry about his.  The git repo passes tests just fine; but when I do `cpanm Toadfarm` or `sudo cpanm Toadfarm`, it's not passing the tests...  D:  I'm sorry, I don't know what to do about this.

```
$ git log -1
commit 72b86230712b474b5432ad2b258dccc0b9888f22
Author: Jan Henning Thorsen <jhthorsen@cpan.org>
Date:   Thu Sep 19 10:10:40 2019 +0900

    Released version 0.81
    
     - Fix t/log.t #27
$ perl Makefile.PL ; make ; make test
Generating a Unix-style Makefile
Writing Makefile for Toadfarm
   ::
All tests successful.
Files=24, Tests=171, 13 wallclock secs ( 0.09 usr  0.05 sys + 12.02 cusr  1.26 csys = 13.42 CPU)
Result: PASS
```

```
$ pwd
/home/ubuntu/.cpanm/latest-build/Toadfarm-0.81
$ perl Makefile.PL ; make ; make test
Generating a Unix-style Makefile
Writing Makefile for Toadfarm
   ::
t/mount-object.t ..... ok   
t/mount-point.t ...... ok    
t/reload.t ........... fatal: Not a git repository (or any of the parent directories): .git
# Reloading
t/reload.t ........... 1/? 
#   Failed test 'exact match for content'
#   at t/reload.t line 44.
#          got: 'nok
# '
#     expected: 'ok
# '
t/reload.t ........... 4/? 
#   Failed test 'possible race condition'
#   at t/reload.t line 49.

#   Failed test 'chdir before git commands'
#   at t/reload.t line 55.
#          got: undef
#     expected: '1'

#   Failed test 'receive USR2 signal'
#   at t/reload.t line 56.
#          got: undef
#     expected: '1'
# Skip reloading

#   Failed test 'exact match for content'
#   at t/reload.t line 61.
#          got: 'nok
# '
#     expected: 'ok
# '

#   Failed test 'chdir before git commands'
#   at t/reload.t line 65.
#          got: undef
#     expected: '1'

#   Failed test 'receive USR2 signal'
#   at t/reload.t line 66.
#          got: undef
#     expected: '1'
# Bad payload
# Status
fatal: Not a git repository: '/home/ubuntu/.cpanm/latest-build/Toadfarm-0.81/.git'
t/reload.t ........... 15/? # Looks like you failed 7 tests of 19.
t/reload.t ........... Dubious, test returned 7 (wstat 1792, 0x700)
Failed 7/19 subtests 
t/rules.t ............ ok   
t/run-as.t ........... skipped: TOADFARM_SUDO_TEST=1
t/secrets.t .......... ok   
t/without-rules.t .... 1/? fatal: Not a git repository: '/dev/null/.git'
t/without-rules.t .... ok   

Test Summary Report
-------------------
t/reload.t         (Wstat: 1792 Tests: 19 Failed: 7)
  Failed tests:  3-6, 9-11
  Non-zero exit status: 7
Files=24, Tests=195, 17 wallclock secs ( 0.12 usr  0.03 sys + 12.35 cusr  1.13 csys = 13.63 CPU)
Result: FAIL
Failed 1/24 test programs. 7/195 subtests failed.
Makefile:925: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255
```

**Comment by s1037989** [comment]
@jhthorsen The CPAN package fails test due to the presence of `.test-all`.  Can you remove that file and re-package?

**Pull request merged**
