### PR TITLE
Include request_id

### PR DESCRIPTION
**Pull request by s1037989**

### CODE REVIEW

**Comment by s1037989** [comment]
@jhthorsen Do you agree with this change?  Should I merge it?
Also, does the .travis.yml file need to get updated?

**Comment by s1037989** [comment]
request_id was added in [7.81](https://github.com/mojolicious/mojo/commit/a8109c0f2c2eb29095f39dc0985a07cfe06ab0e9#diff-253779edd78785613a2a8904fba9563f), and those files both require 8.00, so no update should be necessary.

**Comment by jhthorsen** [comment]
Thanks!

**Comment by s1037989** [comment]
Awesome!  Thanks!

**Pull request merged**
